### ISSUE TITLE
Can we add feature where we can save the graphs instead of dispaling with matplotlib GUI 

### ISSUE THREAD

**Issue by kumarsyamala** [gventuri/pandas-ai#146]
### 🚀 The feature

when we are doing pandasai.run(df,prompt)

In the prompt when we mention to plot or graph output is display instead of that can we save the graph as a images

### Motivation, pitch

I am working on the sample UI integration for pandasai where, we give a prompt the output will be shown, now in the prompt if I mention and the plot or graph the graph is displaying in another popup window.

Instead of that I want to save the plot and read it afterwards, when I kept plt.savefig() its not working

**Comment by gventuri** [comment]
Hey @kumarsyamala, thanks a lot for reporting. What do you mean by "when I kept plt.savefig() its not working"?

**Comment by llohann-speranca** [comment]
Hi. I have run into the same problem and am using the following workaround:

1) Adding `matplotlib.use('agg')` in the beginning of the script where I call the PandasAI agent. That nullifies the `plt.show()` calls, which was raising errors since the agent was not running from the main thread.

2) I have slightly modified the `_task_instruction` in the PandasAI agent, by subclassing the latter:

```python
class CustomPandasAI(PandasAI):
    _task_instruction: str = """
    Today is {today_date}.
    You are provided with a pandas dataframe (df) with {num_rows} rows and {num_columns} columns.
    This is the result of `print(df.head({rows_to_display}))`:
    {df_head}.

    When asked about the data, your response should include a python code that describes the dataframe `df`.
    Using the provided dataframe, df, return the python code to answer the question below. Make sure to prefix the requested python code with {START_CODE_TAG} exactly and suffix the code with {END_CODE_TAG} exactly. If asked to plot, create a pyplot fig and save it locally as "chart.png". 
    Question:
    """
```

_Note:_ that prompt does not prevent the PandasAI to call `plt.show()` and that was quite of important somehow. I believe the last line of generated code is handled in a different manner internally. So it is good that the `plt.savefig()`  is not in the last line ('it is goot that' reads: it was not working in the other way around)

3) When I run the python script from the command line, I must be in the folder I want the chart.png to be saved. Or, you should write a absolute path instead of a relative one in the `_task_instruction`. 

4) After the prompt I manually added the `START_CODE_TAG`:

```python
prompt_suffix = '\n' + START_CODE_TAG
response = pandas_ai(df, prompt=prompt+prompt_suffix, show_code=False)
```

By the way, just a quick check before/instead of possibly opening an issue: could you include '{question}' in the _task_instruction instead of just concatenating the latter with the prompt? That would make life easier whenever we need to 'fine-tune' the instructions.  

After that, everything is working as intended **as long as the LLM actually generates code**. When it doesn't, though, I am not being able to access the LLM's reply to the prompt. That would be enlightening for reformulating a better prompt. Is there an easy way to do so? (should I open another issue for that? Sorry for being new here) 

Finally, the project is wonderful. Thank you very much. You did a especially wonderful job cleaning the generated code and countering hallucinations.

**Comment by jonbiemond** [comment]
The most recent release (0.3.0) adds the ability to Save charts via #188. Once upgraded you can set `save_charts` to True in the constructor call of PandasAI. For example: `PandasAI(llm, save_charts=True)` Note that the chart is saved in addition to being displayed.
