### ISSUE TITLE
Add support for token usage count

### ISSUE THREAD

**Issue by IITGoaPyVidya** [gventuri/pandas-ai#318]
### 🚀 The feature

At the end of every call we should see the token consumed in that call, This will give better understanding of the cost behind making one call.

### Motivation, pitch

I'm comparing different GenAI libraries which revolves around Pandas and would like "token usage" to be possible in PandasAI.

### Alternatives

Other libraries like bambooAI, langchain's pandas agents provides token usage count at the end of every call,

Solution to this issue could be,
1. Use tiktoken library
2. Use langchains callbacks to count tokens

**Comment by gventuri** [comment]
@IITGoaPyVidya thanks a lot for reporting. I don't know how langchain implements it. The problem of using tiktoken is it doesn't necessarily provide an accurate result for the non-openai LLMs that might use a different tokenizer. What do you think?

**Comment by mspronesti** [comment]
@gventuri  @IITGoaPyVidya  There's a rather easy way to do this (in OpenAI): the `OpenAIObject` returned after a call contains a dictionary accessible with the key `"usage"` which contains the following entries:
- `completion_tokens
- `prompt tokens`
- `total_tokens`

For instance, I called `gpt-35-turbo` with the prompt "holaa!!" and I got:
```py
<OpenAIObject chat.completion id=chatcmpl-7WBPbU26C6RLvIdK2saQl21PEWX0A at 0x7fa8180401d0> JSON: {
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "\u00a1Hola! \u00bfEn qu\u00e9 puedo ayudarte hoy?",
        "role": "assistant"
      }
    }
  ],
  "created": 1687904719,
  "id": "chatcmpl-7WBPbU26C6RLvIdK2saQl21PEWX0A",
  "model": "gpt-35-turbo",
  "object": "chat.completion",
  "usage": {
    "completion_tokens": 11,
    "prompt_tokens": 11,
    "total_tokens": 22
  }
}
```
so I guess we might want to add a flag `return_usage` so that, besides returning the completion we can also return the usage.
@gventuri  if you feel this is the way, feel free to assign this to me

**Comment by gventuri** [comment]
@mspronesti sounds great! Just assigned it to you.

We should also temporarily add a default behavior (that is then overridden by OpenAI LLM) so that we explain that this feature is not supported for other LLMs at the moment. What do you think?

**Comment by mspronesti** [comment]
@gventuri I had in mind to have this parameter at the level of `PandasAI` and to propagate it to the backend only if it is of type `BaseOpenAI`, whereas I'd raise a warning (`warnings.warn`) saying the parameter is ignored. Sound good ? :)

**Comment by gventuri** [comment]
@mspronesti sounds perfect I'd say :)

**Comment by mspronesti** [comment]
I've been off for a while, working on it now :) I had a look at the code and, despite accessing the usage data is easy - as explained above -, `PandasAI` is designed to force the LLM to return a string which means that we can't propagate the API response to `PandasAI`.
I have a couple of solutions in mind (from the easiest to the hardest):
* we keep track of the usage info inside `BaseOpenAI` as attributes, which makes it easy to also sum them for multiple calls (e.g. code + conversational answer). `PandasAI` has access to them accessing the `_llm` attribute.
  - **cons:** those attributes MUST be set to 0 after being retrieved; we must retrieve them even when the user doesn't ask for them; we have to set a parameter that only makes sense for OpenAI (see above)

* we create a custom class `LLMOutput` and we use it for each LLM so that inside pandasai we can access the text wrapped inside and the additional metada.
  - **cons**:  this [line](https://github.com/gventuri/pandas-ai/blob/main/pandasai/llm/base.py#L139). This call must be counted too but how to propagate this info outside ? returning more than the generated code would make things harder to handle in the future
  
* we use callbacks, similarly to langchain. This means that each LLM is supposed to optionally receive a list of callbacks and to call them inside `call`. 
   - **cons**: a lot of rework + support for context managers to "copy" what langchain does. 
            
Any opinions ?

**Comment by orkunozturk** [comment]
why closed? what is the conclusion?
