### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by mcconnell340** [gventuri/pandas-ai#332]
I'm trying to use pandasai to pull back answers from a csv file dataframe. I keep getting an error that our index is out of range. Has anyone received this error before and know what typically prompts an index to be out of range when asking a question? Sometimes it gives us the correct answer and other times it tells us our list index is out of range.

The df has pre-calculated columns that we are just trying to reference with question prompts. Each prompt was run separately but we received the error on both. Both also gave us an answer in past trials.

`df = pd.read_excel("PBMilkDecompData.xlsx", sheet_name="Data", header=1, usecols=cols)`
`answer_question_pandas_ai(df, "What is Malk's dollar percent change in the Natural channel")`
`answer_question_pandas_ai(df, "What drove the highest $ Chg for the brand MALK and what was this value, displayed as a currency?")`

Error: '_Unfortunately, I was not able to answer your question, because of the following error:\n\nlist index out of range\n'_

**Comment by BSalita** [comment]
I get the same error with a dataframe of one item. [You need to provide a program](https://github.com/gventuri/pandas-ai/issues/328)

Make it easy on the developer, and yourself, by posting the smallest example of the program. Similar to above link.

**Comment by yassinkortam** [comment]
Can you please copy paste the pandas ai logs for this interaction as well? It should contain the code that it generated and the code that it executed.

**Comment by thimmaiah** [comment]
`import pandas as pd
import os
from pandasai import SmartDataframe
# Instantiate a LLM
from pandasai.llm import OpenAI
from dotenv import load_dotenv
from sqlalchemy import create_engine
import pandas as pd


dbConnection   = None

def init():
    load_dotenv()  # take environment variables from .env.
    sqlEngine       = create_engine('mysql+pymysql://root:root@localhost/IRM_development', pool_recycle=3600)
    global dbConnection
    dbConnection    = sqlEngine.connect()
    
def db_df():
    df = pd.read_sql_table("funds", dbConnection)
    return df

def interact():
    llm = OpenAI(api_token=os.getenv("OPENAI_API_KEY"), verbose=True)
    print(llm)
    
    df = db_df()
    
    sdf = SmartDataframe(df, config={"llm": llm, "llm_options": {"verbose": True}, "verbose": True})
    # sdf.clean_data()
    # # Impute missing values
    # sdf.impute_missing_values()
    # # Generate features
    # sdf.generate_features()
    print(sdf)
    print("##############################")

    response =  sdf.chat('How many funds are there?')
    print(response)
    print("##############################")


    # df.chat('Plot the gdp vs happiness_index')
    # sdf.chat('Plot a bar chart of funds and capital_commitment')


if __name__ == "__main__":
    init()
    interact()  
`

The data frame is as follows
`   id         name  committed_amount_cents                                   details  ...  start_date  target_committed_amount_cents capital_fee_cents other_fee_cents
0   1    Agri Fund            1.120000e+09  Down-sized content-based functionalities  ...         NaT                            0.0               0.0             0.0
1   2   Macro Fund            9.900000e+08      Distributed value-added architecture  ...         NaT                            0.0               0.0             0.0
2   3   Macro Fund            1.150000e+09                Synergized dynamic circuit  ...         NaT                            0.0               0.0             0.0
3   4    SAAS Fund            9.400000e+08           Right-sized didactic capability  ...         NaT                            0.0               0.0             0.0
4   5  SAAS Fund 2            1.220000e+09          Re-engineered analyzing analyzer  ...         NaT                            0.0               0.0             0.0
5   6   Macro Fund            8.200000e+08           Innovative executive moratorium  ...         NaT                            0.0               0.0             0.0

[6 rows x 49 columns]
#`

PandasAi.log

2023-08-17 14:16:48 [INFO] Question: How many funds are there?
2023-08-17 14:16:48 [INFO] Running PandasAI with openai LLM...
2023-08-17 14:16:48 [INFO] Prompt ID: 11b516d0-352e-4a45-aab7-624077b39caa

Error:
Unfortunately, I was not able to answer your question, because of the following error:
list index out of range

**Comment by irshadnilam** [comment]
Having the same issue as the above user.

**Comment by shwetkanwal24** [comment]
list  index out of range same error i am getting is there limit to how much data it can accept like i am providing big excel file of 15,000+ line so is there ant limit because for small files it is working

**Comment by gventuri** [comment]
@aidy-jenkins  @shwetkanwal24 @irshadnilam @thimmaiah, I've just released a patch for this, please upgrade the library :)
