### ISSUE TITLE
"No code found in the response" using Starcoder or Falcon

### ISSUE THREAD

**Issue by EoinHayes1** [gventuri/pandas-ai#340]
### 🐛 Cant get huggingface models to work

Trying to run this in a sagemaker notebook with either Falcon or Starcoder but I keep getting _'No code found in the response'_.  My huggingface api key is working fine so I dont think that is the issue.  

**Code**
```
import pandas as pd
from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder
from pandasai.llm.falcon import Falcon

API_KEY = 'MY_API_KEY'

# Define List of Models
models = {
    "Starcoder": Starcoder,
    "Falcon": Falcon,
}

model_to_run = 'Falcon'

df = pd.DataFrame({
    "country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
    "gdp": [21400000, 2940000, 2830000, 3870000, 2160000, 1350000, 1780000, 1320000, 516000, 14000000],
    "happiness_index": [7.3, 7.2, 6.5, 7.0, 6.0, 6.3, 7.3, 7.3, 5.9, 5.0]
})

# Model Initialisation
llm = models[model_to_run](api_token=API_KEY)
pandas_ai = PandasAI(llm, conversational=False, verbose=True)

# Enter Prompt related to data or Select from Pre-defined for demo purposes.
prompt = 'Plot the histogram of countries showing for each the gpd, using different colors for each bar' #@param [ "What is the relation between GDP and Happines Index", "Plot the histogram of countries showing for each the gpd, using different colors for each bar", "GDP of Top 5 Happiest Countries?"]  {allow-input: true}

response = pandas_ai.run(df, prompt=prompt,
                          is_conversational_answer=False)
```
**Output:** 
```
2023-07-05 13:04:02 [INFO] Question: Plot the histogram of countries showing for each the gpd, using different colors for each bar
2023-07-05 13:04:02 [INFO] Running PandasAI with falcon LLM...
2023-07-05 13:04:02 [INFO] Prompt ID: 01b64ef7-01c7-40a6-b0f4-7c8886cbf46c
2023-07-05 13:04:07 [INFO] 
                        Code generated:
                        ```
                        import matplotlib.pyplot as plt
import pandas as pd

# Read the dataframe
df = pd.read_csv('data.csv')

# Create a histogram
plt.hist(df['gdp'], bins=50, color=df['country'])

# Plot the histogram
plt.show()

                    
2023-07-05 13:04:07 [INFO] 
Code running:
'''
plt.hist(df['gdp'], bins=50, color=df['country'])
plt.show(block=False)
plt.close('all')
'''
No code found in the response

```
&
```
2023-07-05 13:01:34 [INFO] Question: Plot the histogram of countries showing for each the gpd, using different colors for each bar
2023-07-05 13:01:34 [INFO] Running PandasAI with starcoder LLM...
2023-07-05 13:01:34 [INFO] Prompt ID: 12e5a772-683c-4139-9787-e84272c36888
No code found in the response
```

Wondering if anyone has come across this yet?

**Comment by gventuri** [comment]
@EoinHayes1 thanks a lot for the very detailed issue, I've been able to reproduce it and working on a fix!

**Comment by gventuri** [comment]
UPDATE: The issue seems to be related to some LLMs not wrapping the code around ``` tags, making it hard for the parser to figure out whether it's code or text. I'm working on it.

**Comment by sacharya225** [comment]
Hi, I just ran pandasai with Falcon now..I still get the error .. Sorry am I missing something

from pandasai.llm.falcon import Falcon

os.environ["HUGGINGFACE_API_KEY"] = "ABC"
llm_f = Falcon()
pandas_ai = PandasAI(llm=llm_f)
pandas_ai.run(df, "Plot the histogram of countries showing for each the gpd, using different colors for each bar")


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Unfortunately, I was not able to answer your question, because of the following error:
No code found in the response

**Comment by stationeros** [comment]
@gventuri  Is this fixed? I still get that error when I try and use Starcoder

**Comment by gventuri** [comment]
@stationeros should work as of version 0.6.12!

**Comment by AakritiGupta16** [comment]
i am still facing the same issue with this code:

import pandas as pd
from pandasai import PandasAI
from pandasai.llm.falcon import Falcon

llm = Falcon(api_key = os.environ.get('HUGGINGFACE_API_KEY'))

pandas_ai = PandasAI(llm=llm, verbose=True, conversational=True)
# Sample DataFrame
df = pd.read_csv('QueAns-2.csv')

pandas_ai = PandasAI(llm)
pandas_ai(df, prompt='What is the total number of comments?')

I am running this in google colab using the falcon model and this is the output:

Unfortunately, I was not able to answer your question, because of the following error:

No code found in the response

**Comment by jayeshironside** [comment]
I am trying to use starcoder LLM.

**The code i wrote is** 

```
from pandasai import PandasAI
from pandasai.llm.starcoder import Starcoder
import pandas as pd

df = pd.read_csv('employees.csv')

llm = Starcoder(api_token="XYZ")
pandas_ai = PandasAI(llm)
response = pandas_ai.run(df, "Which employee is getting the lowest salary ?")
print(response)
```

**The Output i received is**
Unfortunately, I was not able to answer your question, because of the following error:
No code found in the response.

**Comment by ronaldsholt** [comment]
@jayeshironside @gventuri similar with AzureOpenAI. The problem for me is when trying to engage custom prompts. When I turn off custom prompts, no issues.
