### ISSUE TITLE
Support Llama v2 and Text generation inference 

### ISSUE THREAD

**Issue by mspronesti** [gventuri/pandas-ai#431]
### 🚀 The feature

The feature consists in supporting the LLaMa v2 family of models (especially 70b, 70b-hf, 70b-chat and 70b-chat-hf) and potentially any model supported by text-generation-inference.

### Motivation, pitch

Hi @gventuri, 
I tested some of the llama v2 models (especially 70B and 70B chat) for pandas AI and they seem to be not bad at all. However, they are not available on Huggingface hosted inference API, hence private hosting is the only choice. The most performing way to do this is [text generation inference](https://github.com/huggingface/text-generation-inference) (TGI). 

However, once one writes this `HuggingfaceTextGenerationLLM`, any model supported by TGI can be easily supported in pandasAI, including falcon, starcoder and personal finetunes of those. Here's the proposal: how about I write a versatile class for TGI with a list of "officially" supported models for pandasAI (falcon, starcoder, the llama v2 family) and if the user passes a different one we throw a warning explaining we don't guarantee on the performance ? 

### Additional context

The same proposal above can be applied to the hosted inference API we are currently using for Falcon and Starcoder. In other words, instead of having one class per model we can just use `HuggingfaceLLM` (renaming it to `HuggingfaceEnpointLLM`, for instance) allowing any model but officially supporting only falcon and starcoder, as we are sure of their perfomances.

**Comment by gventuri** [comment]
Hey @mspronesti!
Sounds great, we should definitely have LLaMa 2 integrated, but couldn't find any easy way to add it.
And I really like the approach, let's go for it!

Also, I agree about the second point (maybe with a dedicate ticket). The reason why we haven't "merged" them yet is because I thought about having custom LLM-based prompts at some point in the future to improve the performances, but we can still do something like that having only 1 wrapper or we'll figure out another way.

I've just assigned it to you!

**Comment by ishaan-jaff** [comment]
@gventuri I'm working on this PR here - it add support for llama2 on one interface. If it looks good can I get a review on it ?
