### ISSUE TITLE
"Unfortunately, I was not able to answer your question, because of the following error:\n\n'float' object cannot be interpreted as an integer\n"

### ISSUE THREAD

**Issue by roxannezhao** [gventuri/pandas-ai#548]
### 🐛 Describe the bug

I am running the examples using GooglePalm LLM and got this error. 

```
from pandasai.llm import GooglePalm
llm = GooglePalm(api_key="")

df = pd.DataFrame({
    "country": [
        "United States",
        "United Kingdom",
        "France",
        "Germany",
        "Italy",
        "Spain",
        "Canada",
        "Australia",
        "Japan",
        "China",
    ],
    "gdp": [
        19294482071552,
        2891615567872,
        2411255037952,
        3435817336832,
        1745433788416,
        1181205135360,
        1607402389504,
        1490967855104,
        4380756541440,
        14631844184064,
    ],
    "happiness_index": [6.94, 7.16, 6.66, 7.07, 6.38, 6.4, 7.23, 7.22, 5.87, 5.12],
})

sdf = SmartDataframe(df, config={"llm": llm})

sdf.chat("Plot a histogram of the gdp by country, using a different color for each bar")
```
error: "Unfortunately, I was not able to answer your question, because of the following error:\n\n'float' object cannot be interpreted as an integer\n"
and running sdf.plot_bar_chart(x="country", y="gdp"), no result show up.

**Comment by nautics889** [comment]
Hello, @roxannezhao 

___

I've tried to build the same plot with exactly the code you've provided (except i use OpenAI instead of GooglePalm). The plot has been displayed OK:
![image](https://github.com/gventuri/pandas-ai/assets/31508183/58e18bbb-59ce-4994-9bfc-65b31e96e818)

So, according to the context, i presume the issue is about LLM provider.

___

1. If it's possible, could you try to build a diagram with the same plot and using different LLM (`OpenAI`, `StarCoder`)?
2. Try to add `"verbose": True` in the config dict and let me see output near `Code running` log record.
3. Which version of pandasai you are using?

**Comment by ramujin** [comment]
@roxannezhao @nautics889 I found the resolution to this issue. You must specify top_p, top_k as integers, rather than the default floating point values that the PandasAI constructor assigns. So when you instantiate your LLM, do it like this:

`llm = GooglePalm(api_key=os.environ['PALM_KEY'], temperature=0.0, top_p=1, top_k=1, model="models/text-bison-001")`

Of course, set your temperature, top_p, and top_k settings according to whatever you prefer, and make sure your key is set as an environment variable.

**Comment by roxannezhao** [comment]
Thanks @ramujin it works
