### ISSUE TITLE
Support for Azure Openai apis

### ISSUE THREAD

**Issue by reigN0ne** [gventuri/pandas-ai#96]
### 🚀 The feature

Hi, was wondering if we can get the support for azure openai directly as we have for other llms? Is something happening under development for the cause?

### Motivation, pitch

Azure Openai is a great way to get used to the LLM technology without having to deal with anything else. Hence would love to see the features from pandas-ai implemented for the same, which will help greatly towards creating analysis reports.

**Comment by yzaparto** [comment]
Sounds like a great idea. @reigN0ne is the Azure open ai available to regular users yet? It looks like they are giving access to enterprise customers.

<img width="780" alt="image" src="https://user-images.githubusercontent.com/132240560/237028345-afd1d729-79bc-4cb9-9536-a5a77913d74c.png">

**Comment by UnderTheCraft** [comment]
Would be interested as well.
@yzaparto AFAIK, you might apply to it via [this form](https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7en2Ais5pxKtso_Pz4b1_xUOFA5Qk1UWDRBMjg0WFhPMkIzTzhKQ1dWNyQlQCN0PWcu). But I'm not sure, how long you'll need to wait, since I got access via my company account.

Regarding the implementation, we could check LangChain's version of AzureOpenAI for this feature (see https://github.com/gventuri/pandas-ai/blob/main/pandasai/llm/openai.py).

**Comment by mspronesti** [comment]
I guess this issue can be closed now :)

**Comment by gventuri** [comment]
@mspronesti nice catch, closing!
